### ISSUE TITLE
Lighting Asset Editor - Add New Interchange Asset - Exit Number Value Erroneous when Value contains a Letter Character

### ISSUE THREAD

**Issue by slmessier** [slmessier/eGIS---ASSET-DATA-WAREHOUSE#27]
During the Add workflow for **Interchange** Assets, the system displays the "Exit Number" value erroneously ("NaN") **when the value retrieved from the database includes a letter character (ex. "29A").** There may potentially be a stored procedure or create view statement that requires an updated to properly account for this case.

Example of Error - (Baltimore County IS 695 & Loch Raven Blvd):
![image](https://cloud.githubusercontent.com/assets/4098544/8416190/ff9d92ea-1e71-11e5-8492-b9fd6207f6e7.png)

Corresponding Database Values:
![image](https://cloud.githubusercontent.com/assets/4098544/8416211/28130174-1e72-11e5-9cc5-9bca736ce578.png)

**Comment by slmessier** [comment]
this issue is occurring in SHA Test and SHA PROD

**Comment by TaraF** [comment]
This issue is due to the recent change to the Interchange / Intersection tables to include the letter value (see previous email chain).

Unfortunately, part of the requirements that were modified for Interchange as it evolved, includes writing that exit number back to the database.  The exit number (EXITNUM) in LIGHTING_LIGHTPOLES is a number value (NUMBER(5,0)).   In order to write to the DB correctly, this field needs to be changed to a string (VARCHAR2).   Currently, in flex it is held as a number, due the previous nature of the field.  That can be modified as as string, but the DB also needs to reflect this to work correctly.

**Comment by slmessier** [comment]
this issue has been resolved and successfully tested in SHA TEST.

**Comment by jbenedetta** [comment]
Tested in production and passed.
